#!/usr/bin/python

import DataLog
import sys

if len(sys.argv) < 2 :
	print 'usage : %s dbFileName' % (sys.argv[0])
	sys.exit()
                                                             
version = 2
if len( sys.argv ) >= 3:                                         
	version = int( sys.argv[2] )

DataLog.recoverIdx(sys.argv[1], version)
